### ISSUE TITLE
Code formatting deletes code

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/LanguageServer.jl#106]
See https://discourse.julialang.org/t/warning-vscode-formatter-shredders-code/4663.

@ZacLN we should push a bug fix release for this problem ASAP. Main question is: should we fix this on ``master`` here and then release a new version that has all the other recent stuff you did, or should we instead do a pure bug-fix release that just includes a fix for this issue? I don't have a good understanding of the things you did since the last official release, so probably better if you make that call.

**Comment by ZacLN** [comment]
I can't replicate this on master, let me disable a few not quite working things on master then it's probably best to push a new release (with updated submodules).

**Comment by ZacLN** [comment]
OK, things should be good for a new release. I'm in the middle of moving all linting to the language server but as long as the `CSTParser` submodule is updated this should be fine.

**Comment by davidanthoff** [comment]
Alright, I'm now using commit 235038cf59685 for CSTParser.jl and 4ddc7d8f13dc66f53 for LanguageServer.jl. Those are the ones we should be using, right?

**Comment by ZacLN** [comment]
Yeps thats right for CSTParser, but I've just merged that PR for LS so 3a5cbec907ea4b5244cf97430d5f515b0489f610 is the new commit

**Comment by davidanthoff** [comment]
Alright, RC is here https://github.com/JuliaEditorSupport/julia-vscode/releases/tag/v0.6.2-rc1

I'll try to test it later on Windows, could you give it a quick test on Linux? And then I'll publish it on the marketplace.

**Comment by ZacLN** [comment]
Yup, the vsix works for me

**Comment by davidanthoff** [comment]
Alright, v0.6.2 is published.
