### ISSUE TITLE
Spurious error message

### ISSUE THREAD

**Issue by sbromberger** [JuliaEditorSupport/LanguageServer.jl#111]
See screenshot. Basically, `module Foo` is being tagged as "possible use of undeclared variable Foo".

This is v0.6.2 with Julia v0.6.0.

<img width="860" alt="screen shot 2017-07-11 at 11 30 01" src="https://user-images.githubusercontent.com/941359/28084149-94d96e66-662c-11e7-8924-990bcfbec04d.png">

**Comment by ZacLN** [comment]
fixed
