### ISSUE TITLE
Spurious error message (with transpose)

### ISSUE THREAD

**Issue by sbromberger** [JuliaEditorSupport/LanguageServer.jl#112]
```
function foo()
    a = ones(3, 3)
    b = a'
    return b
end
```
yields
```
file: 'untitled:Untitled-1'
severity: ''
message: 'Unexpected white space around operator'
at: '3,10'
source: 'CSTParser.Diagnostics.Diagnostic'
```
for the `b = a'` line.

**Comment by ZacLN** [comment]
I'm afk for a few days but will fix this on the weekend

**Comment by ZacLN** [comment]
contrary to my previous statement, operator linting is all in and will probably remain in CSTParser so this is fixed [here](https://github.com/ZacLN/CSTParser.jl/commit/807990b3026e354f148e4295bd456d8207a9210a)
