### ISSUE TITLE
Spurious error message (with inner constructor)

### ISSUE THREAD

**Issue by sbromberger** [JuliaEditorSupport/LanguageServer.jl#113]
```
struct Foo
    x::Bool
    Foo() = new(false)
end
```

results in
```
file: 'untitled:Untitled-1'
severity: 'Warning'
message: 'Constructor name does not match type name'
at: '3,5'
source: 'CSTParser.Diagnostics.Diagnostic'
```

**Comment by ZacLN** [comment]
Should be fixed by [this](https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/109)

**Comment by sbromberger** [comment]
Awesome, thanks @ZacLN.

BTW: if you want to test against my LightGraphs package, you'll find a bunch of other stuff. I'm slowly making my way through the issues but at least you know now where they're coming from.

**Comment by ZacLN** [comment]
Yep that's my plan for a bug squashing session as its fairly large, has interaction between nested modules and uses a lot of the language features!

**Comment by sbromberger** [comment]
Let me know how I can help. :)
