### ISSUE TITLE
Malformed textDocument/formatting answer

### ISSUE THREAD

**Issue by pfitzseb** [JuliaEditorSupport/LanguageServer.jl#114]
This is on LanguageServer.jl master:
![screenshot_20170712_135550](https://user-images.githubusercontent.com/6735977/28116559-d958851c-6709-11e7-8acc-f22335433cae.png)

The request that the atom language client sends seems to be well-formed, so this seems to be a LanguageServer.jl problem.

**Comment by ZacLN** [comment]
I'm going to have to get Atom up and running to dig into this, will have a look tomorrow

**Comment by pfitzseb** [comment]
Hm, I suppose if I could figure out how to get at the debugging info from LanguageServer.jl I could help with that ;) So this doesn't happen with VSCode or other clients?

**Comment by ZacLN** [comment]
I can't tell what the problem is from the above, is it just returning an empty message?

**Comment by pfitzseb** [comment]
Well, it's returning an Object (JSON string I guess) which only has `id: 1` in it.

**Comment by ZacLN** [comment]
I couldn't get atom-lsp up and running. Thinking about the above messages though: it looks like  the client is sending a `textDocument/formatting` message before the server is up and running? `id: 1` should be for the first response

**Comment by pfitzseb** [comment]
Hm, I couldn't reproduce this, so closing... 
What troubles did you have with getting the atom language client running?
