### ISSUE TITLE
feature request: highlight where parsing error occurs

### ISSUE THREAD

**Issue by sbromberger** [JuliaEditorSupport/LanguageServer.jl#125]
Right now if you start a docstring with triple quotes, until you put the closing quotes in, the entire file will be underlined in red as a parsing error. (Same goes for any block without a corresponding `end`.) This is really distracting.

Would it be possible to just highlight the section of code that is "in error"? (or, as an alternative, when a block starts, automatically insert `end` statements or closing quotes as necessary?)

**Comment by ZacLN** [comment]
Oops, this was turned off for some reason. https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/126

**Comment by ZacLN** [comment]
So I've been using this with the error appearing at the literal point of parsing failure which, more often than not will be at the end of the file and so is not that helpful. 

What are the thoughts on underlining in green  the start of the expression (that eventually fails to parse) and switching to red after the actual point of failure?

**Comment by sbromberger** [comment]
My preference would be to make red what you're proposing to make green, and not do anything with what you're proposing to make red.

**Comment by davidanthoff** [comment]
We should take a look at the linters for other languages in VS Code and what they do, especially the "official" ones developed by Microsoft. They probably thought hard about it and we can just follow their lead :)
