### ISSUE TITLE
exporting an extended method leads to spurious "exported but not defined" warning.

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/LanguageServer.jl#129]
In a module with something similar to:

```jl
module MM
   using Example
   export hello
   Example.hello(x::Int) = "hello"
end
```

there will be a warning that `hello` is exported even though it is not defined. However, extending a method also defines the method itself in the module.

**Comment by ZacLN** [comment]
I think this is fixed by #128

**Comment by KristofferC** [comment]
Cool, I'll try the master in a while

**Comment by davidanthoff** [comment]
If this is fixed we should close this issue.

**Comment by ZacLN** [comment]
Nope, this is broken. I'll have a look tomorrow and try and work this out

**Comment by ZacLN** [comment]
I think this is going to have to wait for me to remove the `.defs` field of `CSTParser.EXPR` and handle all variable declaration tracking on the LS side of things as it requires knowledge of whether the `hello` binding of `Example` is exported or not.

**Comment by ZacLN** [comment]
fixed
