### ISSUE TITLE
Location of undeclared variable wrong in interpolated string

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/LanguageServer.jl#141]
Using vscode 0.7 beta.

Smallest example (ignore the quotes in top left corner):

![image](https://user-images.githubusercontent.com/1282691/28755839-552790f4-7563-11e7-8ca2-300d98f0af5b.png)

Actually `"$a"` is a smaller example that also shows the squiggly wrong.

A bit larger example where there is a larger desynchronization:

![image](https://user-images.githubusercontent.com/1282691/28755850-7f0ed382-7563-11e7-8d67-48b62e68ed8b.png)

**Comment by ZacLN** [comment]
Oops, linting was supposed to be turned off for strings, I'll delve in

**Comment by davidanthoff** [comment]
It would be cool to have linting inside interpolated code, though :)

**Comment by davidanthoff** [comment]
@ZacLN Let me know whether you want to fix this for the VS Code v0.7.0 release, or for a future release.

**Comment by ZacLN** [comment]
It requires a refactor of Strings in CSTParser, could be easier after I merge the Keno refactor

**Comment by davidanthoff** [comment]
@ZacLN what is the status of this? All done and we can close?

**Comment by ZacLN** [comment]
Fixed
