### ISSUE TITLE
Use of undeclared variable in export

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/LanguageServer.jl#145]
![image](https://user-images.githubusercontent.com/1282691/28786264-0b822d72-7619-11e7-9769-755f2d3ee841.png)

It is interesting because the docs are found.

To note is that ALL exported variables in the package are warned as undefined.

**Comment by ZacLN** [comment]
Is this nearest neighbours again?

**Comment by ZacLN** [comment]
So the problem here is that we're loading modules asynchronously and during the first lint pass as files are parsed it's not yet loaded. If you do an edit the warnings should disappear?

**Comment by KristofferC** [comment]
Yep, that did it

**Comment by ZacLN** [comment]
Cool, I'll maybe add a call to re-run linting after modules get loaded

**Comment by ZacLN** [comment]
https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/146 should do the trick
