### ISSUE TITLE
Format document should remove trailing whitespaces

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/LanguageServer.jl#150]
At the end of each line, it could remove any trailing whitespaces.

**Comment by ZacLN** [comment]
After 0.7.0 is released I'm going to strip all formatting from CSTParser and set it up in it's own package with configurable options (i.e. so it can work as a standalone package as well as hooked up to an editor). 

Tomorrow I'll start an empty project as a placeholder for these issues w/ a wiki laying out what we currently do, and what should be added

**Comment by davidanthoff** [comment]
Yep, that sounds like a perfect plan!

**Comment by ZacLN** [comment]
https://github.com/ZacLN/DocumentFormat.jl
