### ISSUE TITLE
Rename should technically rename things workspace wide, not just in one file

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/LanguageServer.jl#151]
See [here](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_rename). Might be quite tricky to do, but maybe sometimes down the road.

**Comment by ZacLN** [comment]
This is fixed. Related issues:
1. Do we want to allow the renaming of imported names, i.e. renaming calls to `rand`.
2. We could add the ability to rename fieldnames of structs/mutables?

**Comment by davidanthoff** [comment]
I think on 1) I'd say no, but yes on 2), if that struct is defined in the current workspace.
