### ISSUE TITLE
False positive lint on constructor

### ISSUE THREAD

**Issue by mauro3** [JuliaEditorSupport/LanguageServer.jl#164]
A constructor like so:
```
immutable Gridded{T}
...
    function (::Type{Gridded{T}}){T}(...)
        ...
    end
end
```
gets a warning:
```
severity: 'Warning'
message: 'Constructor name does not match type name'
at: '70,5'
source: 'CSTParser.Diagnostics.Diagnostic'
```

Presumably here:
https://github.com/JuliaEditorSupport/LanguageServer.jl/blob/4ae5fdcdeb9413deb9a2a7787b22c03e4362d93e/src/trav/lint.jl#L326

**Comment by ZacLN** [comment]
Cheers , https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/165
