### ISSUE TITLE
Lots of "Possible use of undeclared variable" errors

### ISSUE THREAD

**Issue by sbromberger** [JuliaEditorSupport/LanguageServer.jl#172]
Hi all,

Not sure whether this is the right place to report this issue, but I have approximately 100 "Possible use of undeclared variable" errors, even though they're defined (and exported) in the main module file. Do I have something set up wrong?

To reproduce, just clone LightGraphs.jl and open it up in VSCode, then open a few files (right now, I have `src/distance.jl`, `src/traversals/dfs.jl`, `test/traversals/dfs.jl`, `src/LightGraphs.jl`,  and `src/traversals/maxadjvisit.jl` open).

Thanks for any advice!

**Comment by davidanthoff** [comment]
Are you on Windows? I came across a bug recently about path names that is Windows specific that I believe triggers something like that. I'm still trying to get my repo case narrowed down, but there is an issue with this on Windows.

**Comment by sbromberger** [comment]
OSX:
```
Julia Version 0.6.0
Commit 903644385b* (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin16.5.0)
  CPU: Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
```

FWIW, most of these are in the `test/` suites.

**Comment by davidanthoff** [comment]
Then it is a different bug :) Thanks for reporting.

**Comment by sbromberger** [comment]
Yeah, sorry. It turns out the files open don't really matter.

**Comment by ZacLN** [comment]
This is exclusively down to the looped call to `include` over a vector of strings, we should add a way to handle simple cases of this but I doubt we're going to be able to handle the logic of this file (runtests.jl) (i.e. loop over vector interpolated into a string then a joinpath to a macro call)

**Comment by davidanthoff** [comment]
Ah, yes, I have thought about that issue. I think in general packages often use a lot of clever things like that, but these things are essentially too clever for a good IDE integration. Other examples are packages that create lots of functions via ``eval`` in loops and stuff like that. There is no way that we'll be able to handle those cases.

**Comment by sbromberger** [comment]
Is there a better way to do what I'm doing that won't result in IDE errors? (Failing that, is there a way to exclude `test/` from linting?)

**Comment by davidanthoff** [comment]
I think just having individual lines a la 
````julia
include("community/clustering.jl")
include("community/cliques.jl")
````
etc. should do the trick for now.

The main thing is really to remove the loop over the includes, it is difficult for a static tool like LS to figure out which files will be included without running the loop, which we can't do in a static code analysis tool.

**Comment by ZacLN** [comment]
We can add a `Don't lint file/folder` command

**Comment by sbromberger** [comment]
@ZacLN That seems like it would be generally useful as a package setting.

**Comment by sbromberger** [comment]
Closing in favor of #173.
