### ISSUE TITLE
False positive of "Use of duplicate argument names"

### ISSUE THREAD

**Issue by randy3k** [JuliaEditorSupport/LanguageServer.jl#179]
<img width="698" alt="screen shot 2017-09-02 at 1 24 05 pm" src="https://user-images.githubusercontent.com/1690993/29997468-09d7639c-8fe2-11e7-8e79-5c80cfe18d3b.png">

```julia
function foo(::Type{T}, ::Type{S}) where {T<:Number, S<:Number}
      # blablabla
end
```

**Comment by ZacLN** [comment]
#180
