### ISSUE TITLE
Strategy for getting changes into upstream JuliaParser

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/LanguageServer.jl#18]
@ZacLN Here is one idea how we might be able to avoid a JuliaParser fork, but clearly you need to vet this whether it makes sense. This is based largely on what I see [here](https://github.com/JuliaLang/JuliaParser.jl/compare/master...ZacLN:posinfo).

Essentially the idea is to modify JuliaParser in such a way that by default it returns exactly the same things as without your modifications, but that we can add code here (or in another package) that returns either ``Expr`` objects with position and error info, or maybe in the future even a new ``Expr2`` type or something like that.

Essentially the idea would be this. Say the top level parse function right now has this structure:
````julia
function parse(input)
    bla bla
    throw(D)
    bla bla
end
````
So somewhere in the parse method (or another method called by it) you now want to replace this ``throw(D)`` with a ``return Expr(:error,D)``. We could modify the signature of ``parse`` in this way:
````julia
function parse(input)
    return parse(Val{:default}, input)
end

function parse{T}(::Type{T}, input)
    bla bla
    return foo(T, D)
    bla bla
end

function foo(::Type{Val{:default}}, D)
    throw(D)
end
````
So this would be the code in JuliaParser. In LS, we would add this method:
````
function foo(::Type{Val{:lsparser}}, D)
    return Expr(:error,D)
end
````
I think if this kind of structure would work for all the modifications you need, the JuliaParser folks might be ok with merging this (I hope). The benefit here is this: a) I think there should be no perf penalty relative to the current JuliaParser code, b) none of the location code would actually be in JuliaParser, i.e. we could keep this here in the LS package, experiment and change it quickly etc., c) JuliaParser should look and behave exactly like it does right now for other users, like the Gallium debugger etc.

Do you think something like that could work?

**Comment by ZacLN** [comment]
I think it might, a `ParseState` is passed around to secondary functions when `parse` is called to which we could add an indicator of 'parse_mode' that 1) adds character range info to expressions and 2) disables the error throws. I just need to check that the `ParseState` actually _is_ passed to all the relevant functions.

**Comment by davidanthoff** [comment]
The core idea of my proposal here was to use multi dispatch for this, instead of ``if`` statements. I think the benefit dispatching on a type for the mode of the parser is that a) there shouldn't be any performance overhead (i.e. all the branches are resolved at compile time, and the secondary functions would most likely even be all inlined) and b) one can add a different return type from outside of the ``JuliaParser`` package.

That might be exactly what you had in mind with ``ParseState`` as well, just thought I'd make my point more explicit :)

**Comment by ZacLN** [comment]
Ah OK, I think I see what you mean. We can add a parameter: `ParseState{T}` which is  unobtrusive (a 2 line change) which easily allows us to redefine the 3 small functions to give us location info. This seems much simpler (/more attractive to maintainers) than restating the signatures for all (~100) functions but will this give us the same performance benefits?

There's a problem with the above approach when it come's to replacing the `throw`s in that a `ParseState` is not passed to all functions that can `throw`.
