### ISSUE TITLE
jl_uv_writecb() ERROR: broken pipe EPIPE

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/LanguageServer.jl#185]
When I open the Query.jl package with the latest master version, I get lots of errors like in the title. [Here](https://gist.github.com/davidanthoff/77db0206023eb111c66ab26a0b986335) is the full debug script.

@ZacLN Do you get the same on Linux, or is this a Windows thing?

**Comment by davidanthoff** [comment]
But then things seem to work...

**Comment by ZacLN** [comment]
Can't replicate, though the initial linting of `Query` is painfully slow... I'll look into that.
 
The only thing I can think of off the top of my head is that I've altered the package loading so that it redirects `STDOUT` so that messages don't interfere w the LSP communications

**Comment by ZacLN** [comment]
Actually, even when loaded everything is unworkably slow, was this the case before?

**Comment by davidanthoff** [comment]
Re slow, let me try. What is a specific thing that is slow on your system? I just want to make sure I'll try the same thing.

**Comment by ZacLN** [comment]
Compared to your startup log each file is taking ~5sec to lint on my machine and takes a similar time on any hover. 

I assume it's something in the scoping framework, will investigate...

**Comment by ZacLN** [comment]
OK, this was a result of my package versions being broken, and thus repeatedly trying to load a package. I'll add back in a 'failed to load' list
