### ISSUE TITLE
All diagnostics are removed after startup

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/LanguageServer.jl#187]
I'm loading Query.jl again (with #186), and get [this](https://gist.github.com/davidanthoff/87acaba5d2eff87510cf16ccaf33065f) log.

Starting [here](https://gist.github.com/davidanthoff/87acaba5d2eff87510cf16ccaf33065f#file-gistfile1-txt-L293) the server sends empty ``publishDiagnostics`` messages for each file that delete all the diagnostic messages that the server just sent previously above.

**Comment by ZacLN** [comment]
Can't replicate, can you add a `info(STDERR, stacktrace())` to [lint](https://github.com/JuliaEditorSupport/LanguageServer.jl/blob/master/src/trav/lint.jl#L34) to see where the additional lint is being called from?

**Comment by davidanthoff** [comment]
Ah, my bad, I actually had the linter disabled in the settings :)

But I think the details of that settings implementation are not ideal: when the language server starts, it lints everything and sends those diagnostics to the client, irrespective of the user setting. I think then it next receives the ``workspace/didChangeConfiguration`` message with the info whether the linter is enabled or not, and if not, it then sends a bunch of empty diagnostic messages. Then, when I change the setting to ``true``, I would have expected the lint messages to show up again, but I had to restart VS Code for that setting to take effect.

I guess this probably means the linter should only run after the LS has received the ``workspace/didChangeConfiguration`` message, right?

**Comment by ZacLN** [comment]
Yep sounds good, I'll do a reorganisation of the startup process tomorrow

**Comment by randy3k** [comment]
Should the settings be sent via `initializationOptions` instead?

**Comment by ZacLN** [comment]
No I think not, there's no need to transfer the user setting through two interfaces

**Comment by randy3k** [comment]
I disagree. 

Firstly, not all editors support the capability `workspace/initializationOptions`, if the settings and the diagnostics (#188) are sent via it, it will break the uses of other editors. For instance, it will break sublime text LSP package for sure.

Secondly, `initializationOptions` is the standard way to let a user (not developer) to pass settings to a language server. It says end users to configure the servers. There are no reasons to not use it to send initialization settings at the user level. On the other hand, the implemention of `workspace/initializationOptions` depends on the developer of the package. It maybe not supported as well.

**Comment by ZacLN** [comment]
We don't currently send any initializationOptions to the server from vscode,

**Comment by randy3k** [comment]
Some editors, for example, vim or emacs usually read plugin settings at startup and do not allow dynamic settings updates. Expecting they support `workspace/didChangeConfiguration` may not be reasonable.

**Comment by ZacLN** [comment]
If it's actually impossible to change settings after initialization then we can sort something out, but it'll need a unified approach from all of those client side packages. 

I don't really know where we stand in terms of support for non-vscode clients, it'd be useful to know what other features don't work atm

**Comment by davidanthoff** [comment]
Yeah, I agree with @ZacLN, we really don't want to introduce two ways for settings.

**Comment by randy3k** [comment]
I still think that they are for different purposes. There are no duplications here.

**Comment by randy3k** [comment]
Maybe I have misunderstood some of the changes here. The latest master is still working fine on Sublime Text. Great job, guys!
