### ISSUE TITLE
enum linting still a bit off

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/LanguageServer.jl#189]
When defining an `@enum` the "class" of the enum, e.g `Color` in `@enum Color Red Blue` is still shown as undefined.

**Comment by KristofferC** [comment]
![image](https://user-images.githubusercontent.com/1282691/30905615-9f8dae9a-a375-11e7-8676-633dfb0ababf.png)

**Comment by ZacLN** [comment]
[fix](https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/192)
