### ISSUE TITLE
How to handle workspace wide symbols?

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/LanguageServer.jl#19]
This starts with this observation from @ZacLN:

> We need to have a think about how we want to handle workspace wide parsing and user included Modules, I'm a bit wary of just parsing everything and including it across all files. I think we need some set of rules that determine whether some arbitrary file is related to the one currently open. Maybe based on include(..)'s across the project?

Yes, this is a tricky one... Even in one file this is not simple. Take this file:
````julia
# EDIT ZONE START

# EDIT ZONE END

function foo()
end
````
Should the completion provider actually offer ``foo`` if one starts to type in the edit zone? I think for now that is probably the only sensible answer...

Ok, but on to the real problem. I think ideally we would store the stuff that the parser finds in a file as part of that ``Document``, not as part of some global symbol list. And then the question is, what symbols from other files should the completion provider/doc etc. use in addition to the local symbols. There is one case that is relatively easy: if file A includes file B, then while editing A the LS should also show completions for things defined in B, doc help for things defined in B etc. I think the more complicated situation is that we edit file B, and say file A looks like this:
````julia
module FileA
include("file_C.jl")
include("file_B.jl")
end
````
This is really tricky, because it means that a) actually all the symbols in file B are in the module ``FileA``, but there is no way to learn that from just looking at file_B.jl, and second we should actually show all the symbols/docs etc. from file_C while editing file_B...

I'm not entirely sure how to resolve this... Here are some options:
1. We could build a graph that represents all the includes etc, and while editing file_B we would show symbols from any file that follows the structure of the example above. But one problem is this: file_B might be included by multiple "parent" files, and in different modules. Say there is another file that includes file_B, but here file_B is included in a different module. In what module should the symbols in file_B live now? The module in file_A, or the module in the new file?
2. A more conservative approach would be that we special case this for packages. I.e. we build up a graph, and we detect the case where there is one file in the src folder that has the same name as root folder *and* starts with a module with the same name, and if all of that is the case, we scope all the included files accordingly into that modules namespace.

In both of these cases we would of course have to do everything recursively, i.e. follow multiple includes etc... Plus ``using``, ``import``, ``importall`` etc..

I don't feel I fully comprehend the whole thing at this point, this is certainly a tricky issue... I do think (hope) it is distinct from how we handle ``using`` statements that load other packages...

**Comment by ZacLN** [comment]
Your thoughts follow mine almost exactly.

I think if we mimic actual evaluation as much a possible then we won't have to worry about these logic issues, and it keeps behaviour consistent.

With regards to the first trivial case: 
At the moment when constructing the namespace for a provider action we include all results from the global scope and a module if we're currently in one. For other blocks we're in the interior of we only include definitions that occur before the current position. This can be improved slightly with a tiny bit of work but anything more complicated and we're getting into the position of doing linting twice.

For the second problem I'd lean towards a more 'fuzzy' approach. Include all possible provider solutions and mark as warning diagnositics symbols used whose availability is uncertain. This situation is definitely possible but I'm guessing fairly infrequent in practice. 

This makes my head hurt a bit...

I'm not quite sure what you mean by 'live in'. In my mind we're talking about the scenario of:

```
module FileA
... # code + includes: CodeC
include("file_B.jl")
# rest of code
end

module FileE
... # code + includes: CodeE
include("file_B.jl")
# rest of code
end
```

and when editing file_B we'd get a namespace merging CodeC and CodeE with warnings for symbols not part of the union of CodeC and CodeE. When editing the 'rest of code' of modules A/E this problem disappears as the namespace is constructed without ambiguity.

I think...

**Comment by davidanthoff** [comment]
>  Include all possible provider solutions and mark as warning diagnositics symbols used whose availability is uncertain.

I really like that idea!

> I'm not quite sure what you mean by 'live in'.

Exactly the example you should, and I think your analysis is correct, so that should be ok.

**Comment by ZacLN** [comment]
#48
