### ISSUE TITLE
Support the multi-root folder story

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/LanguageServer.jl#218]
Not clear what that entails, but maybe the next release might be a good vehicle for this?

**Comment by ZacLN** [comment]
We're waiting on the language-server-protocol to add this to the implementation, it should be straightforward from there

**Comment by davidanthoff** [comment]
I think we can start with this already. Apparently the next stable VS Code release (coming out in a few days) will support [this](https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.workspaceFolders.proposed.md) stuff here and enable multi-root across the board.

I think we still should only do this for our v0.9.0 release, but I don't think this is blocked by anything upstream.

**Comment by davidanthoff** [comment]
Here are the relevant docs:
https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.workspaceFolders.proposed.md

and

https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.configuration.proposed.md

I think the ``julia.runlinter`` configuration should really be scoped at the resource level, so we'll have to use that new stuff for getting that config setting. Although we could also keep it a window level configuration for now and deal with it later?
