### ISSUE TITLE
Don't load user packages into the LS process

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/LanguageServer.jl#219]
Long discussed, lets try to tackle this for v0.3.0!

@ZacLN I'd be happy to take a first stab at starting the symbol server process, setting up communication with it etc. One thing that would really help me is if you could point out to me the places in the code where we are querying the system for information that comes from the loaded packages. Essentially maybe just a list of links to code places that we would want to happen in the symbol server.

**Comment by ZacLN** [comment]
The main interface for this is [get_cache_entry](https://github.com/JuliaEditorSupport/LanguageServer.jl/blob/master/src/utilities.jl#L140) which handles requests for hovers etc, which looks up strings/CST expressions against a list of exported names for each loaded module `LanguageServerInstance.loaded_modules`.

There may be another way I access it during linting but I'll check and should probably change that.

**Comment by davidanthoff** [comment]
Moving this to the next version, will take some more time and I think we should rather try to get a new release out before this is done.

**Comment by davidanthoff** [comment]
I took another stab at this, because I think we actually really need this for the 1.0 version to work properly :) I did see the symbol store that is in StaticLint.jl right now, and I think that won't really work well with the whole idea of environments. Yes, we can cache symbols for a given package, but really we would have to store it *per version* of that package, right? And same for julia itself, the StaticLint.jl package folder will be reused for different julia versions, so the store would be shared as well, and would have to be versioned... 

So, here is what I would suggest instead: when the LS starts, it starts a child process that we call the symbol server. One has to specify a specific Pkg3 environment for that symbol server, and then it will serve symbols for the exact package versions that are in that environment. Then, we never load any user packages into the LS process, but that all happens in the symbol server process. That has a bunch of major benefits a) the LS process should become a whole lot more stable, and b) we can automatically reuse precompile files for each environment etc.

The downside of this arrangement is that we introduce more latency into the system: we need to think really hard what and how much information we transfer from the symbol server process to the LS process. My gut feeling would be that we start the symbol server process, next transfer all the symbol information from base (but no docs info) back the LS, then load all the user packages into the symbol server process, then transfer all the symbol info for user packages back to the LS (again, no docs). At that point we stop. When the LS needs doc information for anything, it sends a request to the symbol server, and the symbol server loads it at that moment and sends it back, i.e. we never preload all documentation.

The part about the docs is where I'm slightly nervous: it might be too slow. But I'd saw we try it and see...

I started all of this now with a new package: https://github.com/JuliaEditorSupport/SymbolServer.jl. I think both StaticLint.jl and LanguageServer.jl should take a dependency on it. StaticLint.jl would not instantiate a ``SymbolServerProcess`` instance, but any function in StaticLint.jl that needs access to symbols would accept that as an argument. LanguageServer.jl would instantiate a new ``SymbolServerProcess`` when it starts, and then pass that around as needed.

I think as a first cut, we could start the symbol server to always use the default environment, and then in a later version think hard how we want to support user environments.

@ZacLN, does that sound reasonable?

**Comment by davidanthoff** [comment]
I have a sketch of this now with https://github.com/ZacLN/StaticLint.jl/pull/4 and https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/276. The whole thing does not yet properly work... And performance is horrible, so maybe we do need this damn cache...

And docs don't work...

BUT, I think we no longer load any user packages into the LS process, which I think would be a great benefit. So I would vote that we go with this broad strategy and maybe implement the cache again in SymbolServer.jl for now, or try to speed things up some other way...

**Comment by davidanthoff** [comment]
This is now merged to ``master`` :)
