### ISSUE TITLE
False positive: Possible use of undeclared variable in unary function.

### ISSUE THREAD

**Issue by sunoru** [JuliaEditorSupport/LanguageServer.jl#241]
Something similar to #182 
![1](https://user-images.githubusercontent.com/1469360/34351297-c115cb7e-ea56-11e7-98ca-977ecf313455.PNG)
![2](https://user-images.githubusercontent.com/1469360/34351344-04960c4c-ea57-11e7-9779-4fa874379ad1.PNG)

**Comment by ZacLN** [comment]
fixed by https://github.com/ZacLN/CSTParser.jl/pull/84 and https://github.com/ZacLN/StaticLint.jl/pull/8
