### ISSUE TITLE
Run SnoopCompile.jl on the package

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/LanguageServer.jl#244]

**Comment by KristofferC** [comment]
As a note, I have found that snoopcompile does not have that good effect unless one combines it with sysimg compilation. In some cases snoopcompile actually increases load time so it is important to benchmark the effect of it.

**Comment by davidanthoff** [comment]
Once we have #219 we can use our own private sysimage for the LS server process in the extension, I believe! We should probably be able to pretty much statically compile everything at that point, in theory, right?

**Comment by KristofferC** [comment]
I think so yes. That would be awesome. Is the plan to create the sysimg on the user's computer or by bundling it somehow? I guess there needs to be one bundled sysimg per architecture then.

**Comment by davidanthoff** [comment]
Would probably be more robust to create these on the users computer, right? I imagine something like this:

when the extension tries to start the LS server, it looks whether there is a custom sysimage file in the extension folder. If not, it just starts the LS server like today. At the same time it spawns a new julia process that compiles the custom sysimage.

Then, the next time the LS server is started, it will see that there is a custom user image, and then we start it with that. Does that sound reasonable?

**Comment by KristofferC** [comment]
So running SnoopCompile on the tests of CSTParser and including these in the precompile file, removing any `ANY` annotations, and compiling CSTParser into sysimg I get:

```jl
julia> using CSTParser

julia> @time CSTParser.parse(readstring("base/inference.jl"), true);
  0.204590 seconds (188.09 k allocations: 9.195 MiB)

julia> using BenchmarkTools

julia> @btime CSTParser.parse(readstring("base/inference.jl"), true);
  28.136 ms (147898 allocations: 7.12 MiB)
```

Currently, we have:

```jl
julia> using CSTParser

julia> @time CSTParser.parse(readstring("base/inference.jl"), true);
  3.032584 seconds (335.87 k allocations: 17.190 MiB, 0.18% gc time)

julia> using BenchmarkTools

julia> @btime CSTParser.parse(readstring("base/inference.jl"), true);
  31.633 ms (165376 allocations: 7.71 MiB)
```

**Comment by davidanthoff** [comment]
Wow, the startup improvement is really impressive! Plus, we would do the same thing with LanguageServer.jl and all the other packages as well, so we should see an even better story.

Alright, more motivation to really use a separate process for loading user packages :)
