### ISSUE TITLE
implement textDocument/willSave

### ISSUE THREAD

**Issue by rsrock** [JuliaEditorSupport/LanguageServer.jl#246]
I'm playing around again with emacs-lsp/lsp-mode, largely because lsp-ui popped up.  I'm running into an issue when saving any buffer:

```
ERROR: MethodError: no method matching parse_params(::Type{Val{Symbol("textDocument/willSave")}}, ::Dict{String,Any})
Closest candidates are:
  parse_params(!Matched::Type{Val{:initialize}}, ::Any) at /Users/rrock/.julia/v0.6/LanguageServer/src/provider_misc.jl:41
  parse_params(!Matched::Type{Val{:initialized}}, ::Any) at /Users/rrock/.julia/v0.6/LanguageServer/src/provider_misc.jl:114
  parse_params(!Matched::Type{Val{:shutdown}}, ::Any) at /Users/rrock/.julia/v0.6/LanguageServer/src/provider_misc.jl:121
  ...
Stacktrace:
 [1] parse(::Type{LanguageServer.JSONRPC.Request}, ::Dict{String,Any}) at /Users/rrock/.julia/v0.6/LanguageServer/src/jsonrpc.jl:38
 [2] run(::LanguageServer.LanguageServerInstance) at /Users/rrock/.julia/v0.6/LanguageServer/src/languageserverinstance.jl:36
```

It looks like LanguageServer is not set up to receive this kind of message?

**Comment by rsrock** [comment]
I think I see the problem, will send a PR

**Comment by davidanthoff** [comment]
I thought I had answered this already, but apparently not. Yes, we can just add a handler for that message that does nothing, I think that should work.

**Comment by ZacLN** [comment]
I'll add this as a `struct` and an empty command, not sure how this was missed though... has there been an update to the protocol?

**Comment by davidanthoff** [comment]
I don't really understand it either. When I looked over the protocol it looked like it might be one of those dynamic features? But I don't understand that part ;)
