### ISSUE TITLE
Symbol location is off by one line and should cover all code for methods

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/LanguageServer.jl#25]
I think there is one bug, and one potential improvement:

1. When I flip through the list of symbols in a file, the yellow bar always appears one line above the relevant symbol. My guess is this is another 0 vs 1 based indexing problem.
2. For methods, it would be nice if the yellow bar covered the whole body of code, that is how it is done for e.g. Typescript. I guess this would require us to know where the method body ends, and then returning a ``Location`` that has a range that potentially spans multiple lines?

**Comment by ZacLN** [comment]
There are even more problems: 
1. `functionloc` returns the first line of the `block` , not the signature for functions defined normally.
2. It returns the line of the signature for 'terse' function definitions (i.e. `f(x) = ...`), even if the definition then runs across multiple lines.
3. user defined function's locations include whitespace above them (I'm still unclear on how to handle whitespace without substantial Parser rewrites).
4. I need to narrow down the supplied list of functions by: a) number of arguments for the function and b) types of arguments if inferable  
5. This will definitely return nonsense for functions defined in `include`d files.

For 1/2 : if we move to using a cache for everything in Base/ user modules we can probably do some *slightly* time consuming analysis of the actual file (i.e. look for keyword `function`, etc..)

**Comment by ZacLN** [comment]
#48
