### ISSUE TITLE
Missing UndefVar warning in struct declarations

### ISSUE THREAD

**Issue by KristofferC** [JuliaEditorSupport/LanguageServer.jl#252]
Undefined types in structs are not warned about.

In the function below, they are.

![screen shot 2018-01-18 at 12 03 40](https://user-images.githubusercontent.com/1282691/35095100-a2e50a4a-fc47-11e7-84f6-fae8fdd49568.png)

**Comment by ZacLN** [comment]
Linting skips datatype declarations at the moment, will be fixed w/ StaticLint integration

**Comment by ZacLN** [comment]
Linting skips datatype declarations at the moment. Is fi fixed w/ StaticLint integration

**Comment by ZacLN** [comment]
fixed on master
