### ISSUE TITLE
workspace/executeCommand method error

### ISSUE THREAD

**Issue by andreasnoack** [JuliaEditorSupport/LanguageServer.jl#257]
I'm new to Language Server and trying it out in Sublime. Hovering over deprecated syntax and clicking "fix", I got the error below.

```
ERROR: MethodError: no method matching parse_params(::Type{Val{Symbol("workspace/executeCommand")}}, ::Dict{String,Any}):
Closest candidates are::
parse_params(!Matched::Type{Val{:initialize}}, ::Any) at /Users/andreasnoack/.julia/v0.6/LanguageServer/src/provider_misc.jl:41:
parse_params(!Matched::Type{Val{:initialized}}, ::Any) at /Users/andreasnoack/.julia/v0.6/LanguageServer/src/provider_misc.jl:114:
parse_params(!Matched::Type{Val{:shutdown}}, ::Any) at /Users/andreasnoack/.julia/v0.6/LanguageServer/src/provider_misc.jl:121:
...:
Stacktrace::
[1] parse(::Type{LanguageServer.JSONRPC.Request}, ::Dict{String,Any}) at /Users/andreasnoack/.julia/v0.6/LanguageServer/src/jsonrpc.jl:38:
[2] run(::LanguageServer.LanguageServerInstance) at /Users/andreasnoack/.julia/v0.6/LanguageServer/src/languageserverinstance.jl:36:
```

**Comment by davidanthoff** [comment]
Actually, I'm not sure this is a bug. We certainly don't handle those requests, but I'm not sure Sublime should send that request in the first place? @ZacLN?

**Comment by ZacLN** [comment]
I believe those are server -> client requests

**Comment by andreasnoack** [comment]
Could you explain? Is this Sublime's LSP doing something wrong or is this something that should be added here or something else?

**Comment by davidanthoff** [comment]
I think we both thought this was a bug on Sublime's end, but also weren't really sure... @andreasnoack is this still an issue?

**Comment by andreasnoack** [comment]
Tried to reproduce it but this time I just got a notification that the server crashed. It has been happening relatively often lately so I don't know if it is related to this issue.

**Comment by andreasnoack** [comment]
Let's just close for now. If the same error appears again I'll comment.
