### ISSUE TITLE
Getting symbols doesn't trigger a reparse

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/LanguageServer.jl#26]
When I make some edits to an open file, then the show symbols command shows an empty list.

I think what is happening is that the didChange events invalidate the block information, but then the symbol command doesn't trigger a reparsing?

When I save the file and then open the show symbols command, I do see the full list.

**Comment by ZacLN** [comment]
We're going to need a rethink on how to schedule the reparsing. At the moment it does it on each didChange but this clearly isn't working well. 

To just fix this specific case I've set it to reparse the whole file on symbol requests, #29.

Once I've  got the user modules working I'll come back to this.
