### ISSUE TITLE
"ps: unknown option --o" error

### ISSUE THREAD

**Issue by AmjadHD** [JuliaEditorSupport/LanguageServer.jl#263]
I've been trying to make run the server but it gives me "ps unknown option --o" error
running windows 7, i googled this for a while and found a Cygwin package called procps that supports "-o" option i installed it and replaced ps by procps in languageserver.jl line 36, but the sever shuts down as soon as it's launched. I can't figure out a solution for this, i want the server to work in my sublime text but i can't make the server work in the first place.

**Comment by davidanthoff** [comment]
I think you'll need to provide more context on what you are trying to do here...

**Comment by AmjadHD** [comment]
I have a windows 7 and using Cygwin, when running the server (from the command line with bash languageserver.sh) it gives me an error "ps unknown option --o", then ps doesn't support -o option like in linux, i tried to solve this by installing "procps" cygwin package, this time no errors BUT the server stops working seconds after launch. Any Ideas ?

**Comment by davidanthoff** [comment]
Hm, I won't be able to help with that, that is a configuration I'm not familiar enough with. I'll leave this open, maybe someone else can chime in.

**Comment by AmjadHD** [comment]
Thanks, but finally i got this working, I didn't use the languageserver.sh though, i just used the command: < using LanguageServer; server = LanguageServer.LanguageServerInstance(STDIN, STDOUT, false); server.runlinter = true; run(server); > ,directly.

**Comment by AmjadHD** [comment]
maybe having an equivalent batch file for windows will solve this as 'languageserver.sh' requires installing cygwin.
