### ISSUE TITLE
How to run it in command line?

### ISSUE THREAD

**Issue by shoorlyne** [JuliaEditorSupport/LanguageServer.jl#267]
I try to run the language server in command line in Ubuntu 16.04 like this:

`root@731913e32ca0:/LanguageServer.jl-master/src# julia LanguageServer.jl `

And I get this error:

```
ERROR: LoadError: ArgumentError: Module JSON not found in current path.
Run `Pkg.add("JSON")` to install the JSON package.
Stacktrace:
 [1] _require(::Symbol) at ./loading.jl:435
 [2] require(::Symbol) at ./loading.jl:405
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] process_options(::Base.JLOptions) at ./client.jl:305
 [6] _start() at ./client.jl:371
while loading /LanguageServer.jl-master/src/LanguageServer.jl, in expression starting on line 3
```

What's the correct way to run it in command line?

**Comment by davidanthoff** [comment]
[This](https://github.com/JuliaEditorSupport/julia-vscode/blob/165508de47f7843f8e391c464ce52282149423c7/scripts/languageserver/main.jl#L28) shows how we start it in VS Code.

**Comment by davidanthoff** [comment]
I'm going to close this, as there doesn't seem to be anything to do on our end. If not, let me know and we'll reopen.
