### ISSUE TITLE
Add an option to disable the candidate limit

### ISSUE THREAD

**Issue by IngoHeimbach** [JuliaEditorSupport/LanguageServer.jl#269]
First: Thanks for this language server. Using a completion / linter backend makes Julia coding easier and even more fun! 😃 

I use [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) as a Client for this language server and [YouCompleteMe](https://github.com/Valloric/YouCompleteMe) as completion engine. YouCompleteMe uses a cache for completion candidates to provide fast as you type candidate matching. However, that cache function cannot work with this language server since [the candidate list is restricted to 200 entries](https://github.com/JuliaEditorSupport/LanguageServer.jl/blob/master/src/requests/textDocument.jl#L251) (also see [this issue](https://github.com/Valloric/YouCompleteMe/issues/3099) for further discussion). Would it be possible to add an option to always get the full candidate list?

**Comment by ZacLN** [comment]
The 200 completion limit has been removed
