### ISSUE TITLE
Server initialization failed.

### ISSUE THREAD

**Issue by shoorlyne** [JuliaEditorSupport/LanguageServer.jl#271]
I am trying to connect Monaco editor to the Julia language server (LS), on Julia 0.6.4/Ubuntu 16.04. I am having some issue initializing the Julia language server (LS).

The initialize request sent from the editor looks like this:

`{"jsonrpc":"2.0","id":0,"method":"initialize","params":{"rootPath":null,"rootUri":"/home","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true},"didChangeConfiguration":{"dynamicRegistration":false},"didChangeWatchedFiles":{"dynamicRegistration":false},"symbol":{"dynamicRegistration":true},"executeCommand":{"dynamicRegistration":true}},"textDocument":{"synchronization":{"dynamicRegistration":true},"completion":{"completionItem":{"snippetSupport":true},"dynamicRegistration":true},"hover":{"dynamicRegistration":true},"signatureHelp":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"definition":{"dynamicRegistration":true},"codeAction":{"dynamicRegistration":true},"codeLens":{"dynamicRegistration":true},"documentLink":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true}}},"initializationOptions":{"storagePath":"/","gocodeCompletionEnabled":true},"trace":"off"}}`

However, the Julia LS doesn't respond, causing the editor to err with "Server initialization failed". The Julia LS doesn't print any message either.

The settings I use to start the Julia LS look like this:

```
"command": "/julia-9d11f62bcb/bin/julia",
        "args": [
            '/julials/LanguageServer.jl-master/src/LanguageServer.jl',
            '--debug=yes'
        ]
}
```
The Julia LS is spawned from a node.js server which communicate with the Julia LS via stdio.

I need some help to understand what the issue is, and how to fix it. Thanks!

**Comment by ZacLN** [comment]
fixed by https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/288
