### ISSUE TITLE
autocompletion problems

### ISSUE THREAD

**Issue by pfitzseb** [JuliaEditorSupport/LanguageServer.jl#303]
With [this](https://gist.github.com/pfitzseb/61878904ac003b7283402cd96d4ef198) manifest (and the neovim language client) I'm getting:
```
[ Info: TIME:0.44
[ Info: RECEIVED: {"jsonrpc":"2.0","method":"textDocument/completion","params":{"position":{"character":1,"line":8},"textDocument":{"uri":"file:///home/pfitzseb/.julia/dev/Gadfly/src/coord.jl"}},"id":22}
[ Info: 
ERROR: MethodError: no method matching iterate(::StaticLint.Binding)
Closest candidates are:
  iterate(!Matched::Core.SimpleVector) at essentials.jl:589
  iterate(!Matched::Core.SimpleVector, !Matched::Any) at essentials.jl:589
  iterate(!Matched::ExponentialBackOff) at error.jl:171
  ...
Stacktrace:
 [1] indexed_iterate(::StaticLint.Binding, ::Int64) at ./tuple.jl:63
 [2] process(::LanguageServer.JSONRPC.Request{Val{Symbol("textDocument/completion")},LanguageServer.TextDocumentPositionParams}, ::LanguageServerInstance) at /home/pfitzseb/.julia/packages/LanguageServer/C1B4E/src/requests/textDocument.jl:297
 [3] run(::LanguageServerInstance) at /home/pfitzseb/.julia/packages/LanguageServer/C1B4E/src/languageserverinstance.jl:46
 [4] top-level scope at none:0
```

**Comment by ZacLN** [comment]
I can't see how this would happen on the current configuration so will close this, let me know if it reoccurs.

**Comment by pfitzseb** [comment]
What set of package versions do I need now? Is `master` on all the explicit LanguageServer.jl dependencies okay?

**Comment by ZacLN** [comment]
Yes that should work

**Comment by KristofferC** [comment]
Checking in a Manifest here might make sense.

**Comment by davidanthoff** [comment]
> Checking in a Manifest here might make sense.

But then we need to keep that up-to-date :) Given that the main place where all of this comes together is in the VS Code extension, and we don't use environments/manifests there at all, I think there is a high likelihood that any manifest file here would just be outdated in a matter of hours...
