### ISSUE TITLE
False import flag when package is not installed in default environment.

### ISSUE THREAD

**Issue by gdkrmr** [JuliaEditorSupport/LanguageServer.jl#316]
I think that the reason that the `OnlineStatsBase` imports get flagged is because `OnlineStatsBase` is not installed in "~/.julia/environments/v1.0". Find the repo [here](https://github.com/gdkrmr/WeightedOnlineStats.jl).

![screenshot_2018-11-22_11-16-27](https://user-images.githubusercontent.com/12512930/48896563-2e800d00-ee48-11e8-87b2-276d77d75602.png)

`LanguageServer` is run as:

```julia
using LanguageServer, Sockets, SymbolServer;
server = LanguageServer.LanguageServerInstance(
        stdin, stdout, false,
        "/path/to/MyPkg", "",
        Dict()
);
server.runlinter = true;
run(server);
```

stdout gives only two lines:
```
[ Info: Started symbol server
[ Info: StaticLint store set
```

**Comment by davidanthoff** [comment]
We don't properly support non default environments yet, that will have to wait for the next release...

**Comment by davidanthoff** [comment]
We now have a PR that fixes env handling. I'm going to close this issue in favor of that PR. Fingers crossed we'll have a working version of env support soon.
