### ISSUE TITLE
Pkg API change

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/LanguageServer.jl#320]
Reported by @KristofferC on Slack:

> By the way, SymbolServer.jl fails on 1.1-rc1 due to some small changes in Pkg internals: https://gist.github.com/ararslan/533cf231d32d87a6f80bf47d38de3182#file-symbolserver-log

My response:
> The offending lines seems this:
https://github.com/JuliaEditorSupport/SymbolServer.jl/blob/16881b632c522124ec74111cfb447c2f6f3451f4/src/clientprocess/from_static_lint.jl#L147
Is there an alternative API for the same thing that we can use? Ideally something that works on 1.0 and 1.1?

**Comment by davidanthoff** [comment]
@KristofferC, any recommendation what we could do about this? Ideally we would release a patch quickly, right now the extension is broken on julia 1.1...

**Comment by StefanKarpinski** [comment]
cc also @00vareladavid

**Comment by 00vareladavid** [comment]
`c.env.project.other["deps"]` should work.

This occurs because `ctx.env.project` is no longer a string-based dictionary. It is now a struct. But we did keep the raw dictionary around for compatibility reasons.

**Comment by fredrikekre** [comment]
https://github.com/JuliaEditorSupport/SymbolServer.jl/pull/15

**Comment by davidanthoff** [comment]
Hurray! I'll release a new version ASAP.

**Comment by tk3369** [comment]
I'm curious - 
Did we have this problem due to a breaking change in Pkg from Julia 1.0 to 1.1?  If semantic versioning works properly then shouldn't everything be non-breaking?.... or perhaps it's is using an un-exported API?

**Comment by fredrikekre** [comment]
It was undocumented Pkg internals, but there are plans for an official query API to avoid things like this in the future, see https://github.com/JuliaLang/Pkg.jl/pull/1086
