### ISSUE TITLE
[`workspace/didChangeConfiguration`'s `setting` can be `Nothing`

### ISSUE THREAD

**Issue by FelipeLema** [JuliaEditorSupport/LanguageServer.jl#324]
[`workspace/didChangeConfiguration`'s `setting`](https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeConfiguration) can be `Nothing`.

This can be fixed by testing against `r.params["settings"] != nothing` in `process(r::JSONRPC.Request{Val{Symbol("workspace/didChangeConfiguration")},Dict{String,Any}}, server)` *before* doing `haskey(…)`

Related to https://github.com/joaotavora/eglot/issues/59 (I also found it because `eglot` reports "nothing" there).

**Comment by ZacLN** [comment]
Cheers, fixed on master
