### ISSUE TITLE
Neovim language server description does not work with Julia 1.0 / latest LanguageServer.jl

### ISSUE THREAD

**Issue by slensgra** [JuliaEditorSupport/LanguageServer.jl#327]
The current description for vim / neovim throws the argument error mentioned in this issue: https://github.com/JuliaEditorSupport/LanguageServer.jl/issues/318

It took me some diving into the source code to figure out what the arguments needed to be, but I eventually landed on the following which is working well for me. Would it be possible to update the description for vim / neovim so others don't have to go spelunking? I'd make a pull request into the wiki but it looks like that isn't supported.

I had to install the `SymbolServer` and `StaticLint` packages also to allow me to do the top level importing.

```
let g:LanguageClient_serverCommands = {
\   'julia': ['julia', '--startup-file=no', '--history-file=no', '-e', '
\       using LanguageServer;
\       using Pkg;
\       import StaticLint;
\       import SymbolServer;
\       env_path = dirname(Pkg.Types.Context().env.project_file);
\       debug = false; 
\       
\       server = LanguageServer.LanguageServerInstance(stdin, stdout, debug, env_path, "", Dict());
\       server.runlinter = true;
\       run(server);
\   ']
\ }
```

**Comment by davidanthoff** [comment]
I think you should just be able to click "Edit" on the wiki page and make changes?

**Comment by slensgra** [comment]
Ah! I'll do that

**Comment by AtsushiSakai** [comment]
@slensgra @davidanthoff Hi. I updated the wiki page based on the above comment.

**Comment by AtsushiSakai** [comment]
I'm using vim-lsp + LanguageServer.jl currently 
However, it doesn't work now correctly. (see: https://github.com/prabirshrestha/vim-lsp/issues/140 )
If I found a solution for it, I will update the wiki.

**Comment by davidanthoff** [comment]
Is there anything left to do here? If so, please open a new issue!
