### ISSUE TITLE
update wiki page for emacs

### ISSUE THREAD

**Issue by tpapp** [JuliaEditorSupport/LanguageServer.jl#329]
https://github.com/JuliaEditorSupport/LanguageServer.jl/wiki/Emacs is somewhat outdated. The link in the README could just point to https://github.com/non-Jedi/lsp-julia.

@non-Jedi

**Comment by non-Jedi** [comment]
@tpapp I'll edit the wiki when I get a chance to, but fyi the wiki for this repo is actually editable by any github user afaict. ;)

**Comment by non-Jedi** [comment]
done

**Comment by tpapp** [comment]
@non-Jedi: point taken, but my understanding of the setup requirements is mostly experimental ("this worked for me"), so there is a concern that the information I post there could be bogus or specific to my setup. As the maintainer of the Emacs package, you have more specific expertise -- thanks for doing it.
