### ISSUE TITLE
Not working with Julia 1.1 and neovim

### ISSUE THREAD

**Issue by ronisbr** [JuliaEditorSupport/LanguageServer.jl#330]
I tried to install LanguageServer.jl with Julia 1.1 and Neovim and, even following the new instructions in #327, I keep having a timeout.

**Comment by korsbo** [comment]
I'm having the same issue.

**Comment by gipaetusb** [comment]
Same issue here, tried both 1.1 and 1.0.3
call plug#begin('~/.vim/plugged')
  Plug 'JuliaEditorSupport/julia-vim'                               " Julia pack for Vim
  Plug 'autozimu/LanguageClient-neovim', {'branch': 'next', 'do': 'bash install.sh'}
  Plug 'ncm2/ncm2'                                                  " AutoCompletion!
  Plug 'roxma/nvim-yarp'
call plug#end()

au User Ncm2Plugin call ncm2#register_source({
        \ 'name' : 'css',
        \ 'priority': 9,
        \ 'subscope_enable': 1,
        \ 'scope': ['css','scss'],
        \ 'mark': 'css',
        \ 'word_pattern': '[\w\-]+',
        \ 'complete_pattern': ':\s*',
        \ 'on_complete': ['ncm2#on_complete#delay', 180, 
                       \  'ncm2#on_complete#omni', 'csscomplete#CompleteCSS'],
        \ })

" julia
let g:default_julia_version = '1.1'

" language server
let g:LanguageClient_autoStart = 1
let g:LanguageClient_serverCommands = {
  \   'julia': ['julia', '--startup-file=no', '--history-file=no', '-e', '
  \       using LanguageServer;
  \       using Pkg;
  \       import StaticLint;
  \       import SymbolServer;
  \       env_path = dirname(Pkg.Types.Context().env.project_file);
  \       debug = true; 
  \       
  \       server = LanguageServer.LanguageServerInstance(stdin, stdout, debug, env_path, "", Dict());
  \       server.runlinter = true;
  \       run(server);
  \   ']
  \ }
nnoremap <silent> K :call LanguageClient_textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient_textDocument_definition()<CR>
nnoremap <silent> <F2> :call LanguageClient_textDocument_rename()<CR>

):

**Comment by angeris** [comment]
+1. Is there a current workaround? Is it stable with 1.0 or something of the like? I do (almost all) of my development in Vim, so this is pretty blocking.

**Comment by davidanthoff** [comment]
The latest version of the language server should now work with julia 1.1. I don't know anything about VIM, so not sure whether there might be more problems.

**Comment by angeris** [comment]
@davidanthoff Ok, for some reason it did seem to work on some instances, but I now can't replicate the behavior. This may not be a `LanguageServer.jl` bug (and if it is, this is generally unclear).

Thanks!

**Comment by lassepe** [comment]
I think this can be closed.

**Comment by korsbo** [comment]
Agreed, for some magical reason, it is now working fine for me too.

**Comment by ronisbr** [comment]
It is indeed working perfectly and it is AMAZING!:wq
