### ISSUE TITLE
not working on master (1.2.0-DEV.219)

### ISSUE THREAD

**Issue by tpapp** [JuliaEditorSupport/LanguageServer.jl#331]
I could not get LanguageServer working on the above version, while it is working fine on Julia 1.1 ([see this discussion](https://discourse.julialang.org/t/using-lsp-julia/20085/6)).

I am happy to dig more into this issue if necessary, just need some help how to start.

**Comment by davidanthoff** [comment]
I think we are also broken right now on julia 1.1....

**Comment by davidanthoff** [comment]
I'm closing this for now, will track getting our testing working again in https://github.com/JuliaEditorSupport/LanguageServer.jl/issues/289.
