### ISSUE TITLE
no method matching String(::Nothing)

### ISSUE THREAD

**Issue by gdkrmr** [JuliaEditorSupport/LanguageServer.jl#341]
`LanguageServer.jl` started crashing with `lsp-julia`, tried with both all the latest release versions of the packages and latest master, Julia version is 1.1:
```
[ Info: Started symbol server
[ Info: StaticLint store set
ERROR: MethodError: no method matching String(::Nothing)
Closest candidates are:
  String(!Matched::String) at boot.jl:318
  String(!Matched::Array{UInt8,1}) at strings/string.jl:39
  String(!Matched::Base.CodeUnits{UInt8,String}) at strings/string.jl:77
  ...
Stacktrace:
 [1] LanguageServer.TextDocumentItem(::Dict{String,Any}) at /home/me/.julia/packages/LanguageServer/2C2HB/src/protocol/protocol.jl:25 (repeats 2 times)
 [2] parse_params(::Type{Val{Symbol("textDocument/didOpen")}}, ::Dict{String,Any}) at /home/me/.julia/packages/LanguageServer/2C2HB/src/requests/textdocument.jl:2
 [3] parse(::Type{LanguageServer.JSONRPC.Request}, ::Dict{String,Any}) at /home/me/.julia/packages/LanguageServer/2C2HB/src/jsonrpc.jl:38
 [4] run(::LanguageServerInstance) at /home/me/.julia/packages/LanguageServer/2C2HB/src/languageserverinstance.jl:44
 [5] top-level scope at none:0
```

**Comment by jmulcahy** [comment]
The cause of this seems to be that Emacs’ lsp-mode is setting languageId to nothing. That eventually propagates through to dictionary that fails to serialize into a string.

What should languageId be set to? Is it standardized? If not, should this package accept nothing as a valid value?

**Comment by gdkrmr** [comment]
where is `languageld` set exactly? I cannot find a variable with that name.

**Comment by jmulcahy** [comment]
It's sent from the LSP client, which is `lsp-mode` set up by `lsp-julia` in this case. The request is deserialized here: https://github.com/JuliaEditorSupport/LanguageServer.jl/blob/b21c2cebf2173858fc8e6f78d8fb18ed778f7b19/src/protocol/document.jl#L7

There are several ways to fix this problem.
1. Edit the line in the link above so that `languageId` has the type `Union{Nothing,String}` rather than just `String`.
2. Add Julia to the list of languages here: https://github.com/emacs-lsp/lsp-mode/blob/09f76651183e1b4a083b9f3708a55b2bfd5cc220/lsp-mode.el#L500.
3. There is probably something you can do in `lsp-julia`.

It's a bit of an odd problem because Julia isn't on the list of official language specifiers here: https://microsoft.github.io/language-server-protocol/specification#textdocumentitem. I'm not familiar enough with LSP to say where the fix should be made. Given that this package only ever intends to provide a LS for Julia, the first option feels reasonable to me, although it technically violates the LSP spec.

**Comment by davidanthoff** [comment]
We should certainly get onto that official list of languages!

**Comment by gdkrmr** [comment]
That was certainly a good example of why the right font is important, I was looking for `languageld` and not `languageId` :-). 

Thanks for figuring this out, it was certainly nothing obvious. I created a PR with `lsp-mode` (https://github.com/emacs-lsp/lsp-mode/pull/827).

**Comment by gdkrmr** [comment]
After updating `lsp-mode` from Melpa `lsp-julia` is working for me now. Not sure if we should leave this issue open until we make `LanguageServer.jl` and `lsp-julia` more robust. Feel free to close.

**Comment by ZacLN** [comment]
LanguageId should be a String, shouldn't it? https://microsoft.github.io/language-server-protocol/specification

**Comment by gdkrmr** [comment]
Maybe it should default to an empty string, so that it does not get converted to `nothing`.

**Comment by ZacLN** [comment]
Isn't it better in the long run for lsp-julia to obey the protocol?

**Comment by gdkrmr** [comment]
I have no clue about the internal workings of the lsp protocol I will try to figure out if `lsp-julia` can do something about this. I have also no clue how this trickles through the layers of `LanguageServer.jl` and if this could be made more robust (or at least give a nicer error) by stricter typing or default values (maybe it shouldn't be robust to avoid such specification errors). I don't think you should deviate from the lsp protocol.

**Comment by ZacLN** [comment]
Hi, I don't think this is an issue on our side (i.e. this package). In terms of robustness - the lsp is extensively documented so I think it's reasonable for the server to crash if it's getting non compliant messages from the client. 

I don't understand enough about the emacs implementation but looks like PR ref'd above should do it?

**Comment by gdkrmr** [comment]
I made an additional change to `lsp-julia`, just to be on the safe side, thanks for helping out with this!

**Comment by ZacLN** [comment]
Awesome, could you post a link to the PR so I can start to get a better understanding of how it works?

**Comment by gdkrmr** [comment]
The PR is here: https://github.com/non-Jedi/lsp-julia/pull/11
I don't really know how lsp-mode handles this internally, they have a list that maps modes to language id. The only thing I do is adding a mapping for `julia-mode`.

This is actually in the readme for `lsp-mode` and we should have done this from the beginning:
https://github.com/emacs-lsp/lsp-mode/blame/master/README.org#L225
