### ISSUE TITLE
`TextDocumentContentChangeEvent` must allow no `range` and no `rangeLength`

### ISSUE THREAD

**Issue by oxinabox** [JuliaEditorSupport/LanguageServer.jl#52]
https://github.com/JuliaEditorSupport/LanguageServer.jl/blob/50bb880bceb2acb1605e82b4e00b02196ac06f94/src/protocol.jl#L165

According to the [spec](https://github.com/Microsoft/language-server-protocol/blob/20cf6216a7e30da2afcafea32e5e2593ebe7c65e/protocol.md#didchangetextdocument-notification):

The `range` and the `rangeLength` fields do not have to be provided.

> * An event describing a change to a text document. If range and rangeLength are omitted
> * the new text is considered to be the full content of the document.

I guess this never came up before because VScode would automatically fill in those fields with `0` and `length(document)` ? 

----

My work around, at least to let me continue testing is:

```julia
  function TextDocumentContentChangeEvent(d::Dict)
      if length(d)==1
          text = d["text"]
          rangeLength = length(text)
          lines = split(text, "\n")
          TextDocumentContentChangeEvent(Range(0,0, length(lines)-1, length(lines[end])-1), rangeLength, text)
      else
          TextDocumentContentChangeEvent(Range(d["range"]), d["rangeLength"], d["text"])
      end
  end

```

**Comment by ZacLN** [comment]
Yep seems sensible, and we can make the same change for all other interfaces/structs that are sent from the server to client with optional parameters. I think we should bump the language server protocol up to version 3.0 at the same time.

**Comment by ZacLN** [comment]
#48
