### ISSUE TITLE
bug in formatting chopping away code

### ISSUE THREAD

**Issue by musm** [JuliaEditorSupport/LanguageServer.jl#54]
`    Libc.free(outbuf); return convert(Csize_t, 0)`

get's chopped to
`
return convert(Csize_t, 0)
`

**Comment by ZacLN** [comment]
Hmm, I'm not getting the same effect over here.

Can I get you to turn debugging on for these (undoubtedly numerous) reports?
Swap  `ls_debug_mode` for `true` in [this](https://github.com/JuliaEditorSupport/julia-vscode/blob/master/scripts/languageserver/main.jl#L27)

This'll let you dump out the LS-> vscode messages so I can narrow this down

**Comment by musm** [comment]
try this file https://github.com/JuliaIO/HDF5.jl/blob/master/src/blosc_filter.jl
and note what happens on l117

**Comment by ZacLN** [comment]
Got it, the indent checker wasn't taking into account semicolon.
[fix](https://github.com/ZacLN/CSTParser.jl/commit/9ec9cd052ec7ed4ab5e7023eb9577aa5556bca45)

**Comment by musm** [comment]
thanks
