### ISSUE TITLE
Better integration with built-in vscode git 

### ISSUE THREAD

**Issue by ZacLN** [JuliaEditorSupport/LanguageServer.jl#56]
Currently shifting branches can mess up the state of LS workspace

**Comment by davidanthoff** [comment]
Does this mean it just generally can't deal with file edits that are not made via VS Code? I.e. if I open a file in a workspace in some other text editor and save the change, ideally it would still work, right?

**Comment by davidanthoff** [comment]
Can we close this? We think that is fixed, right?

**Comment by ZacLN** [comment]
Yup
