### ISSUE TITLE
Do we still need the julia.runlinter setting?

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/LanguageServer.jl#61]
Is the new linter always running? This is related to #60, if I make this setting ``false`` that bug goes away.

**Comment by ZacLN** [comment]
I'll fix #60, I think we should leave this as an (unused) setting for now. The test framework for the linting is working well except in the presence of non-basic macros which I think will be a complicated issue to fix so the ability to turn off some portion of the linting will be key.
