### ISSUE TITLE
"Go To Symbol in file..." command highlights too many lines

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/LanguageServer.jl#62]
The list is really cool that shows up, but when I go through the list with the up and down arrow and look at the yellow highlights, it always highlights too many lines. I think it always seems to highlight everything up to the next code block, including the first line of the next code block. Ideally it would only highlight e.g. the function itself, i.e. everything up to and including the ``end`` statement.

Here is an example:
![image](https://cloud.githubusercontent.com/assets/1036561/26560583/ae55e1bc-446c-11e7-941d-65f4dd2b3cc9.png)

**Comment by ZacLN** [comment]
Yep it's counting trailing ws of all expressions as the same block, it's happening with the hover as well. I'll add a helper function to subtract the length of white space from an expressions span

**Comment by ZacLN** [comment]
ref: #70

**Comment by davidanthoff** [comment]
This seems fixed now.
