### ISSUE TITLE
Timing of diagnostic messages

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/LanguageServer.jl#65]
Right now diagnostic messages only show up in the PROBLEMS panel in VS Code once a file has been opened. Could we instead just send all diagnostics back as soon as we have them, even if the file was never opened? Those messages then still show up in the PROBLEMS panel, and I think that is generally nicer and more standard in the VS Code universe.

**Comment by davidanthoff** [comment]
Is this actually resolved already? Not sure...

**Comment by ZacLN** [comment]
Nope, I haven't worked this out yet

**Comment by ZacLN** [comment]
Now fixed
