### ISSUE TITLE
False positive from package linter

### ISSUE THREAD

**Issue by davidanthoff** [JuliaEditorSupport/LanguageServer.jl#68]
When I package lint [this](https://github.com/davidanthoff/DataValueArrays.jl) package, I get two info messages. Both complain that I have packages declared in REQUIRE that I don't seem to be using. The complaint about ``DataValues`` I understand, because that one is used via the ``@reexport`` macro and so can't really be detected. But the complaint about ``Reexport`` seems incorrect, there is a ``using Reexport`` [here](https://github.com/davidanthoff/DataValueArrays.jl/blob/master/src/DataValueArrays.jl#L5)?

**Comment by ZacLN** [comment]
I can't replicate this, could you run [this](https://gist.github.com/ZacLN/177378f18fd53f9275b72b871ba35aba) and tell me the output
(and check you're on master)
