### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by innerlee** [JuliaEditorSupport/LanguageServer.jl#93]
I believe this line of code need to handle the exception caused by removing the file before reading. Otherwise, an error would make the language server fail, and restart in vscode.

https://github.com/JuliaEditorSupport/LanguageServer.jl/blob/master/src/provider_misc.jl#L48

**Comment by ZacLN** [comment]
Do you mean an insertion of `!isfile(filepath) && continue` above it?

**Comment by innerlee** [comment]
Maybe, I don't know the best way to do this. Initially I thought about a try...catch block.

**Comment by ZacLN** [comment]
fix #94
